update all libraries to symfony 6.4
mapado/rest-client-sdk-bundle pull request #18
Opened 2024-01-11 16:21 UTC by didier2l

### Nouveau comportement

Mise à jour des dépendances de la lib vers symfony 6.4

Nécessaire pour la PR https://github.com/mapado/ticketing/pull/4457

2024-02-22 13:26 UTC, jdeniau requested changes

2024-02-22 13:26 UTC, jdeniau commented on src/RequestAwareRestClient.php
> +        $request = $requestStack->getMainRequest();
Surement pas OK avec symfony 2.7 et 3, etc.

2024-02-23 09:32 UTC, didier2l commented on src/RequestAwareRestClient.php
> +        $request = $requestStack->getMainRequest();
bien vu l'ancien. je drop le support <5.0

2024-02-23 09:33 UTC, didier2l commented on composer.json
> +        "mapado/rest-client-sdk": "^0.33 || ^0.34 || ^0.35 || ^0.36 || dev-update-symfony-6-4"
:warning: la branche temporaire sf6

2024-03-20 08:45 UTC, merged